### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by lizhiustc** [fe1ixxu/Mixed-Gradient-Few-Shot#1]
Hi,  a really nice work ! I have a question. I notice that you compare  your work with https://aclanthology.org/2021.acl-long.447.pdf in XNLI experiment. But it seems that you didn't experiment on their few shot dataset (https://github.com/fsxlt/buckets) , which is important for model scores. Maybe because their few shot dataset (https://github.com/fsxlt/buckets) have too many buckets(40) ? And  I'm curious about the reviewers' opinions from NAACL about this points .  Is that acceptable ?   Thanks !

**Comment by fe1ixxu** [comment]
Thanks for your interest in this paper! Zhao et al. also indeed have a nice work on a public few-shot dataset extracted from Xtreme. We don't use them because of different shot selection and codebase designs. One can use their dataset, or use ours to **have arbitrary buckets and arbitrary shot selection by using variable `K` and different random seeds** (in the paper, we use seed=1,2,3,4,5). The reviewers didn't mention anything about the dataset we used. Any experiments designed scientifically and rationally are acceptable by the NLP community.
